name       : itstool
version    : 2.0.5
release    : 5
source     :
    - https://github.com/itstool/itstool/archive/2.0.5.tar.gz : 97f98e1a5f8f49239e4256570ecfe12caf88b7cfdb4fcb40f4b761ce7ea2a8c3
license    :
    - GPL-3.0-or-later
compnent   : programming
summary    : XML to PO and back again
builddeps  :
    - docbook-xml
rundeps    :
    - docbook-xml
description: |
    Itstool extracts messages from XML files and outputs PO template files, then merges translations from MO files to create translated XML files. It determines what to translate and how to chunk it into messages using the W3C Internationalization Tag Set (ITS).
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
