name       : itstool
version    : 2.0.6
release    : 7
source     :
    - https://github.com/itstool/itstool/archive/2.0.6.tar.gz : bda0b08e9a1db885c9d7d1545535e9814dd8931d5b8dd5ab4a47bd769d0130c6
homepage   : http://itstool.org/
license    :
    - GPL-3.0-or-later
component  : programming
summary    : XML to PO and back again
description: |
    Itstool extracts messages from XML files and outputs PO template files, then merges translations from MO files to create translated XML files. It determines what to translate and how to chunk it into messages using the W3C Internationalization Tag Set (ITS).
builddeps  :
    - docbook-xml
rundeps    :
    - docbook-xml
setup      : |
    %patch -p1 < $pkgfiles/itstool-2.0.5-fix-crash-wrong-encoding.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
